apiVersion: cloud.oceanbase.com/v1
kind: OBCluster
metadata:
  name: ob-test
  namespace: obcluster
spec:
  imageRepo: oceanbasedev/oceanbase-cn
  tag: v3.1.3-10100042022051821
  imageObagent: oceanbasedev/obagent:0.3
  clusterID: 1
  topology:
    - cluster: cn
      zone:
        - name: zone1
          region: region1
          nodeSelector:
            topology.kubernetes.io/zone: zone1
          replicas: 1
        - name: zone2
          region: region1
          nodeSelector:
            topology.kubernetes.io/zone: zone1
          replicas: 1
        - name: zone3
          region: region1
          nodeSelector:
            topology.kubernetes.io/zone: zone1
          replicas: 1
      parameters:
        - name: log_disk_size
          value: "40G"
  resources:
    cpu: 2
    memory: 10Gi
    storage:
      - name: data-file
        storageClassName: "local-path"
        size: 50Gi
      - name: data-log
        storageClassName: "local-path"
        size: 50Gi
      - name: log
        storageClassName: "local-path"
        size: 30Gi
      - name: obagent-conf-file
        storageClassName: "local-path"
        size: 20Gi